require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/model_names", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ModelName. As you add validations to ModelName, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ModelName.create! valid_attributes
      get model_names_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      model_name = ModelName.create! valid_attributes
      get model_name_url(model_name)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_model_name_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      model_name = ModelName.create! valid_attributes
      get edit_model_name_url(model_name)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ModelName" do
        expect {
          post model_names_url, params: { model_name: valid_attributes }
        }.to change(ModelName, :count).by(1)
      end

      it "redirects to the created model_name" do
        post model_names_url, params: { model_name: valid_attributes }
        expect(response).to redirect_to(model_name_url(ModelName.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ModelName" do
        expect {
          post model_names_url, params: { model_name: invalid_attributes }
        }.to change(ModelName, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post model_names_url, params: { model_name: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested model_name" do
        model_name = ModelName.create! valid_attributes
        patch model_name_url(model_name), params: { model_name: new_attributes }
        model_name.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the model_name" do
        model_name = ModelName.create! valid_attributes
        patch model_name_url(model_name), params: { model_name: new_attributes }
        model_name.reload
        expect(response).to redirect_to(model_name_url(model_name))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        model_name = ModelName.create! valid_attributes
        patch model_name_url(model_name), params: { model_name: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested model_name" do
      model_name = ModelName.create! valid_attributes
      expect {
        delete model_name_url(model_name)
      }.to change(ModelName, :count).by(-1)
    end

    it "redirects to the model_names list" do
      model_name = ModelName.create! valid_attributes
      delete model_name_url(model_name)
      expect(response).to redirect_to(model_names_url)
    end
  end
end
